
spring:
  application:
    name: config-server
  profiles:
    active: native
    group:
      prod:
        - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 7090
