server:
  port: 7096
spring:
  neo4j:
    uri: bolt://localhost:7688
    authentication:
      username: neo4j
      password: password
  data:
    neo4j:
      database: sapphire.account
logging:
  file:
    name: logs/account-management/spring-boot.log