spring:
  cloud:
    gateway:
      routes:
        - id: member-management
          uri: lb:http://MEMBER-MANAGEMENT
          predicates:
            - Path=/api/v1/sapphire/member/secured/**, /api/v1/sapphire/account/secured/**
          filters:
          - AuthenticationFilter # Apply authentication for secured end points
        - id: member-management-public
          uri: lb:http://MEMBER-MANAGEMENT
          predicates:
            - Path=/api/v1/sapphire/member/public/**
          filters: [] # No authentication filter
        - id: premium-billing
          uri: lb:http://PREMIUM-BILLING
          predicates:
            - Path=/api/v1/sapphire/premium-billing/**
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/sapphire/auth/**
      discovery:
        locator:
          enabled: true
server:
  port: 7092
