eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    port: ${EUREKA_PORT:7091}
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  cloud:
    config:
      override.system-properties: false
application:
  auth-service:
    host: ${AUTH_SERVICE_HOST:localhost}
    port: ${AUTH_SERVICE_PORT:7093}
  user-info:
    user-id: X-USER-ID
    username: X-USER-NAME
    service-id: X-SERVICE-ID
    account-type: X-ACCOUNT-TYPE