eureka:
  instance:
    hostname: localhost
    port: 7091
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  cloud:
    config:
      override.system-properties: false
application:
  user-info:
    user-id: X-USER-ID
    username: X-USER-NAME
    service-id: X-SERVICE-ID
    account-type: X-ACCOUNT-TYPE