application:
  config:
    premium-billing-url: http://localhost:7092/api/v1/sapphire/premium-billing
spring:
  data:
    mongodb:
      username: membermanagementadmin
      password: password
      host: localhost
      port: 27019
      database: member-management
      authentication-database: member-management
server:
  port: 7094
logging:
  file:
    name: logs/member-management/spring-boot.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        data:
          jpa: INFO